---

- name: Add Deluge PPA
  apt_repository:
    repo: ppa:deluge-team/ppa
    state: present

- name: Install Deluge Daemon
  apt:
    name: ['deluged', 'deluge-web', 'deluge-console']
    update_cache: true
    state: present
    cache_valid_time: 3600


