---

- name: Include OS-specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Create deluge group
  ansible.builtin.group:
    name: "{{ deluge_service_group }}"
    state: present
  become: true
  become_user: root

- name: Get all users
  ansible.builtin.getent:
    database: passwd
    key:

- name: Set fact if user exists
  set_fact:
    user_exists: true
  when: deluge_service_user in ansible_facts.getent_passwd

- name: Set fact if user does not exist
  set_fact:
    user_exists: false
  when: deluge_service_user not in ansible_facts.getent_passwd

- name: Create deluge user
  ansible.builtin.user:
    name: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    comment: "Deluge Service"
    create_home: true
    home: "{{ deluge_home }}"
    system: true
  when:
    - not user_exists
  become: true
  become_user: root

- name: Ensure Deluge download directory
  ansible.builtin.file:
    path: "{{ deluge_download_location }}"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: '0755'
    recurse: true
    state: directory
  become: true
  tags:
    - deluge

- name: Include systemd configs
  include: systemd.yml
