---
# deluged
- name: Create deluged user service directory
  ansible.builtin.file:
    path: "{{ deluge_user_service_dir }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  tags:
    - deluge
  become: true

- name: Copy user service config
  ansible.builtin.template:
    src: "user.conf.j2"
    dest: "{{ deluge_user_service_dir }}user.conf"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Install deluged service
  ansible.builtin.template:
    src: "deluged.service.j2"
    dest: "/etc/systemd/system/deluged.service"
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - deluge

# deluge-web
- name: Create deluge-web user service directory
  ansible.builtin.file:
    path: "{{ deluge_web_user_service_dir }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  when:
    - deluge_web
  tags:
    - deluge
  become: true

- name: Copy user service config
  ansible.builtin.template:
    src: "user.conf.j2"
    dest: "{{ deluge_web_user_service_dir }}user.conf"
    owner: root
    group: root
    mode: 0755
  become: true
  when: deluge_web
  tags:
    - deluge

- name: Install deluge-web service
  ansible.builtin.template:
    src: "deluge-web.service.j2"
    dest: "/etc/systemd/system/deluge-web.service"
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - deluge

# Start services
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable and start deluged service
  ansible.builtin.systemd:
    name: deluged
    enabled: true
  become: true
  changed_when: false

- name: Enable and start deluge-web service
  ansible.builtin.systemd:
    name: deluge-web
    enabled: true
  become: true
  when: deluge_web
  changed_when: false
