---

- name: Check for deluged user service dir
  stat:
    path: "{{ deluge_user_service_dir | dirname }}"
  register: _deluge_user_service_dir
  tags:
    - deluge

- name: Create deluged user service dir
  file:
    path: "{{ deluge_user_service_dir }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  when:
    - _deluge_user_service_dir is defined
    - not _deluge_user_service_dir.stat.exists
  tags:
    - deluge
  become: true

- name: Copy user service config
  template:
    src: "user.conf.j2"
    dest: "{{ deluge_user_service_dir }}user.conf"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Check for deluge-web user service dir
  stat:
    path: "{{ deluge_web_user_service_dir | dirname }}"
  register: _deluge_web_user_service_dir
  when: deluge_web
  tags:
    - deluge

- name: Create deluge-web user service dir
  file:
    path: "{{ deluge_web_user_service_dir }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  when:
    - _deluge_web_user_service_dir is defined
    - not _deluge_web_user_service_dir.stat.exists
    - deluge_web
  tags:
    - deluge
  become: true

- name: Copy user service config
  template:
    src: "user.conf.j2"
    dest: "{{ deluge_web_user_service_dir }}user.conf"
    owner: root
    group: root
    mode: 0755
  become: true
  when: deluge_web
  tags:
    - deluge

- name: Install deluged services
  template:
    src: "deluged.service.j2"
    dest: "/etc/systemd/system/deluged.service"
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - deluge

- name: Install deluge-web services
  template:
    src: "deluge-web.service.j2"
    dest: "/etc/systemd/system/deluge-web.service"
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - deluge

- name: enable and start Deluged service
  systemd:
    name: deluged
    enabled: true
  become: true
  changed_when: false

- name: enable and start Deluge services
  systemd:
    name: deluge-web
    enabled: true
  become: true
  when: deluge_web
  changed_when: false
