---

- name: Install services
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - deluged.service
    - deluge-web.service
  become: true

- name: enable and start Deluge services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - deluged
    - deluge-web
  become: true
  changed_when: false
