---
- name: Ensure GnuPG
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags:
    - deluge

- name: Add repository
  ansible.builtin.apt_repository:
    repo: deb [trusted=yes] http://ppa.launchpad.net/deluge-team/stable/ubuntu/ xenial main
    state: present
  become: true
  tags:
    - deluge

- name: Add apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: C5E6A5ED249AD24C
    state: present
  become: true
  tags:
    - deluge

- name: Ensure deluged
  ansible.builtin.apt:
    name:
      - deluged
      - deluge-console
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags:
    - deluge

- name: Ensure deluge-web
  ansible.builtin.apt:
    name: deluge-web
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: deluge_web
  tags:
    - deluge
    - deluge_web
