---
- name: Ensure deluge group
  ansible.builtin.group:
    name: "{{ deluge_service_group }}"
    state: present
  become: true

- name: Ensure deluge user
  ansible.builtin.user:
    name: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    comment: "Deluge Service"
    create_home: true
    home: "{{ deluge_home }}"
    system: true
  become: true