---
- name: Ensure deluge service group
  ansible.builtin.group:
    name: "{{ deluge_service_group }}"
    state: present
  become: true
  tags:
    - deluge

- name: Ensure deluge service user
  ansible.builtin.user:
    name: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    comment: "Deluge Service"
    create_home: true
    home: "{{ deluge_home }}"
    system: true
  become: true
  tags:
    - deluge