---
# deluged
- name: Ensure deluged unit file
  ansible.builtin.template:
    src: "deluged.service.j2"
    dest: "/etc/systemd/system/deluged.service"
    owner: root
    group: root
    mode: u+rw-x,g+rw-x,o+r-wx
  become: true
  tags:
    - deluge

# deluge-web
- name: Ensure deluge-web unit file
  ansible.builtin.template:
    src: "deluge-web.service.j2"
    dest: "/etc/systemd/system/deluge-web.service"
    owner: root
    group: root
    mode: u+rw-x,g-rwx,o-rwx
  when: deluge_web
  become: true
  tags:
    - deluge
    - deluge_web

# systemd
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  tags:
    - deluge
