---

- name: Checking if we should template the deluge config file
  template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_config_dir }}/core.conf"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    mode: '0640'
  check_mode: True
  register: _deluge_core_conf
  tags:
    - deluge_config

- name: deluge-web config file needs updating. deluge should be stopped beforehand
  service:
    name: 'deluged'
    state: stopped
  when: _deluge_core_conf|changed
  tags:
    - deluge_config

- name: Copy deluge configuration file
  template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_home }}.config/deluge/core.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_user }}"
    mode: 0640
    backup: true
  become: true
  notify: restart deluge-web
  tags:
    - deluge_config

- name: Checking if we should template the deluge-web config file
  template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_config_dir }}/web.conf"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    mode: '0640'
  check_mode: True
  register: _deluge_web_conf
  tags:
    - deluge_config

- name: deluge-web config file needs updating. deluge-web should be stopped beforehand
  service:
    name: 'deluge-web'
    state: stopped
  when: _deluge_web_conf|changed
  tags:
    - deluge_config

- name: Copy deluge-web configuration file
  template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_home }}.config/deluge/web.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_user }}"
    mode: 0640
    backup: true
  become: true
  notify: restart deluge-web
  tags:
    - deluge_config
  when: deluge_web
