---

- name: Check for config dir
  stat:
    path: "{{ deluge_config_dir | dirname }}"
  register: _deluge_config_dir
  tags:
    - deluge
    - deluge_config

- name: Create config directory
  file:
    path: "{{ deluge_config_dir }}"
    state: directory
    mode: '0750'
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
  when:
    - _deluge_config_dir is defined
    - not _deluge_config_dir.stat.exists
  tags:
    - deluge
    - deluge_config
  become: true

- name: Checking if we should template the deluge config file
  template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_config_dir }}/core.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: 0640
  check_mode: true
  become: true
  register: _deluge_core_conf
  tags:
    - deluge_config

- name: deluged config file needs updating. deluge should be stopped beforehand
  service:
    name: deluged
    state: stopped
  become: true
  when: _deluge_core_conf is changed
  tags:
    - deluge_config

- name: Copy deluge configuration file
  template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_config_dir }}/core.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: 0640
    backup: true
  become: true
  notify: restart deluged
  tags:
    - deluge_config

- name: Checking if we should template the deluge-web config file
  template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_config_dir }}/web.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: 0640
  check_mode: true
  become: true
  register: _deluge_web_conf
  changed_when: false
  tags:
    - deluge_config

- name: deluge-web config file needs updating. deluge-web should be stopped beforehand
  service:
    name: deluge-web
    state: stopped
  become: true
  when: _deluge_web_conf is changed
  changed_when: false
  tags:
    - deluge_config

- name: Copy deluge-web configuration file
  template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_config_dir }}/web.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: 0640
    backup: true
  become: true
  notify: restart deluge-web
  when: deluge_web
  changed_when: false
  tags:
    - deluge_config
