---

- name: Add Deluge PPA
  apt_repository:
    repo: ppa:deluge-team/ppa
    state: present

- name: Add deluge group
  group:
    name: "{{ deluge_group }}"
    state: present

- name: Add deluge user
  user:
    name: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    comment: "Deluge Service"
    create_home: true
    home: /var/lib/deluge
    system: true

- name: Install Deluge Daemon
  apt:
    name: ['deluged', 'deluge-web', 'deluge-console']
    update_cache: true
    state: present
    cache_valid_time: 3600

- name: Update Deluge Daemon Service
  template:
    src: deluged.service.j2
    dest: /etc/systemd/system/deluged.service
    owner: root
    group: root
    mode: 0755

- name: Update Deluge Web Service
  template:
    src: deluge-web.service.j2
    dest: /etc/systemd/system/deluge-web.service
    owner: root
    group: root
    mode: 0755

- name: enable and start Deluge Daemon service
  systemd:
    name: deluged
    state: restarted
    enabled: true

- name: enable and start Deluge Web service
  systemd:
    name: deluge-web
    state: restarted
    enabled: true

- name: Create logging directory
  file:
    path: /var/log/deluge
    state: directory
    mode: '0750'
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
