---
- name: Ensure Deluge installation
  ansible.builtin.include: installation/main.yaml

- name: Ensure Deluge configuration
  ansible.builtin.include: configuration/main.yaml

- name: Ensure services are active
  ansible.builtin.include: services.yaml