---
- name: check for supported OS
  assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: Start Setup
  include: setup/main.yml

- name: Start Configure
  include: configure.yml
