---
- name: Check for supported OS
  ansible.builtin.assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: Start Install
  ansible.builtin.include: install/main.yml

- name: Start Configure
  ansible.builtin.include: configure.yml

- name: Configure users
  ansible.builtin.include: users.yml
