---
- name: Ensure deluged service is enabled and started
  ansible.builtin.systemd:
    name: deluged
    enabled: true
  become: true

- name: Ensure deluge-web service is enabled and started
  ansible.builtin.systemd:
    name: deluge-web
    enabled: true
  become: true
  when: deluge_web