---
- name: Ensure auth file
  ansible.builtin.file:
    path: "{{ deluge_config_dir }}/auth"
    state: touch
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: u+rw-x,g+rw-x,o-rwx
    modification_time: preserve
    access_time: preserve
  become: true
  tags:
    - deluge
    - deluge_config

- name: Checking if there are Deluge users to be added
  ansible.builtin.lineinfile:
    dest: "{{ deluge_config_dir }}/auth"
    regexp: "^{{ item.name }}:{{ item.password }}:{{ item.access_level }}$"
    line: "{{ item.name }}:{{ item.password }}:{{ item.access_level }}"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: '0640'
    state: present
  check_mode: true
  register: _deluge_users_to_add
  with_items: "{{ deluge_users_to_add }}"
  become: true
  tags:
    - deluge
    - deluge_config

- name: Checking if there are Deluge users to be removed
  ansible.builtin.lineinfile:
    dest: "{{ deluge_config_dir }}/auth"
    regexp: "^{{ item }}"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: '0640'
    state: absent
  check_mode: true
  register: _deluge_users_to_remove
  with_items: "{{ deluge_users_to_remove }}"
  become: true
  tags:
    - deluge
    - deluge_config

- name: Deluge users need to be added or removed. deluged should be stopped beforehand
  ansible.builtin.service:
    name: deluged
    state: stopped
  when: _deluge_users_to_add.changed or _deluge_users_to_remove.changed
  become: true
  tags:
    - deluge
    - deluge_config

- name: Add deluge users
  ansible.builtin.lineinfile:
    dest: "{{ deluge_config_dir }}/auth"
    regexp: "^{{ item.name }}:{{ item.password }}:{{ item.access_level }}$"
    line: "{{ item.name }}:{{ item.password }}:{{ item.access_level }}"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: '0640'
    backup: true
    state: present
  with_items: "{{ deluge_users_to_add }}"
  become: true
  notify: restart deluged
  tags:
    - deluge
    - deluge_config

- name: Remove deluge users
  ansible.builtin.lineinfile:
    dest: "{{ deluge_config_dir }}/auth"
    regexp: "^{{ item }}"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: '0640'
    backup: true
    state: absent
  with_items: "{{ deluge_users_to_remove }}"
  become: true
  notify: restart deluged
  tags:
    - deluge
    - deluge_config
