---
- name: Verifying deluged port is open
  wait_for:
    host: 127.0.0.1
    port: "{{ item }}"
    state: started
    delay: 0  # No wait before first check (sec)
    timeout: 30  # Stop checking after timeout (sec)
  ignore_errors: true
  loop:
    - 58846
  tags:
    - verify
    - deluge

- name: Verifying deluge-web port is open
  wait_for:
    host: 127.0.0.1
    port: "{{ item }}"
    state: started
    delay: 0  # No wait before first check (sec)
    timeout: 30  # Stop checking after timeout (sec)
  ignore_errors: true
  loop:
    - 8112
  when: deluge_web
  tags:
    - verify
    - deluge
    - deluge_web