---
- name: restart deluged
  systemd:
    name: deluged
    state: restarted

- name: restart deluge-web
  systemd:
    name: deluge-web
    state: restarted

- name: start deluged and web
  systemd:
    name: deluged
    state: started
  notify: restart deluge-web
