---
- name: restart deluged
  systemd:
    name: deluged
    state: restarted

- name: restart deluge-web
  systemd:
    name: deluge-web
    state: restarted

- name: start deluged and web
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - deluged
    - deluge-web
