---
- name: restart deluged
  service:
    name: deluged
    state: restarted

- name: restart deluge-web
  service:
    name: deluge-web
    state: restarted

- name: start deluged and web
  service:
    name: ['deluged','deluge-web']
    state: started
