---
- name: Ensure config directory
  ansible.builtin.file:
    path: "{{ deluge_config_dir }}"
    state: directory
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: u+rwx,g-rwx,o-rwx
  become: true
  tags:
    - deluge
    - deluge_config

- name: Ensure download directory
  ansible.builtin.file:
    path: "{{ deluge_download_location }}"
    state: directory
    recurse: true
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: u+rwx,g+rx-w,o+rx-w
  become: true
  tags:
    - deluge