---
- name: Ensure config directory
  ansible.builtin.file:
    path: "{{ deluge_config_dir }}"
    state: directory
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: u+rwx,g-rwx,o-rwx
  become: true
  tags:
    - deluge
    - deluge_config

- name: Ensure download directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: u+rwx,g+rwx,o+rwx
  become: true
  loop:
    - "{{ deluge_download_location }}"
    - "{{ deluge_move_completed_path }}"
    - "{{ deluge_torrentfiles_location }}"
    - "{{ deluge_autoadd_location }}"
  tags:
    - deluge